### ISSUE TITLE
Entry level usage of Pocket_Stats?

### ISSUE THREAD

**Issue by jason-mehmel** [nlbao/pocket_stats#14]
Hello! I found your app when Pocket themselves linked to it. I was asking if there were any up to date projects that were tracking Pocket stats!

Is this project something that would need an extra layer for general use? I'm relatively technical but not a programmer and only have some general understanding of the command line.

Looking at the readme.md, I see graphics at the bottom, are these visualizations only created AFTER taking all the previous steps?

When the readme has the step Load Cached Data and then Extract Useful Information, do those steps need to be taken each time you want to examine your Pocket Stats? Or at least if you want the data to be up to date?

I'm running Ubuntu 20.04. Could I write bash scripts to collect all the data and then run the web app?

Thank you for any help you can provide! Thank you for all of your work on this app.

**Comment by nlbao** [comment]
Hi Jason, 

Thank you for reaching out!

> Is this project something that would need an extra layer for general use? 

Actually, yes, I have plans to publish this as a web application, so people can access it online without running anything in their machines. But currently I'm out of bandwidth to do that.
For now, you still can run it locally, though.

> Looking at the readme.md, I see graphics at the bottom, are these visualizations only created AFTER taking all the previous steps?

No, in order to see the visualizations, you only need to do:
* Prepare [prerequisites](https://github.com/nlbao/pocket_stats#prerequisites)
* Run `pip3 install pocket-stats`
* Set necessary environment variables:
```shell
    export POCKET_STATS_CONSUMER_KEY='<your_pocket_consumer_key>'
    export POCKET_STATS_ACCESS_TOKEN='<your_pocket_access_token>'
```
* Start the web server: `python3 -m pocket_stats webapp`

> When the readme has the step Load Cached Data and then Extract Useful Information, do those steps need to be taken each time you want to examine your Pocket Stats? Or at least if you want the data to be up to date?

* "Load Cached Data" only loads the data that was already downloaded from Pocket. It doesn't refresh the data.
* "Extract Useful Information" section is for examining the data using Python, so you don't need to run them yourself. :)
* If you want the data to be up to date, run the command lines in [Fetch data from the Pocket server and cache it](https://github.com/nlbao/pocket_stats#fetch-data-from-the-pocket-server-and-cache-it) and then restart your webapp server.

> I'm running Ubuntu 20.04. Could I write bash scripts to collect all the data and then run the web app?

Yes, after installed all the components, a bash script can be like this:
```shell
    export POCKET_STATS_CONSUMER_KEY='<your_pocket_consumer_key>'
    export POCKET_STATS_ACCESS_TOKEN='<your_pocket_access_token>'
    python3 -m pocket_stats fetch-data --overwrite_cache  # run this command only when you need to update the data
    python3 -m pocket_stats webapp
```

Btw, you said that **Pocket themselves linked to this pocket_stats repo**? May I ask where did you see that (I tried to search on their website but found nothing ...)? Some pictures may help, too.

**Comment by jason-mehmel** [comment]
Hey! Thanks for writing back!

And thanks for some explanations on the process. If I get it set up and some bash scripts working, I'll let you know! I can also (sometime later) help write or edit the README for newbie users.

As for the link from Pocket themselves, it was on twitter! I'll link it here and screenshot it too.

https://twitter.com/Pocket/status/1336848645061275652

![pocket linking to project](https://user-images.githubusercontent.com/3622823/101991564-c983f380-3c6a-11eb-8275-51dc99bc3958.png)

**Comment by jason-mehmel** [comment]
I should add, I see a few users replying to the end-of-year tweets by Pocket where they are celebrating user stats (I'm in the top 1% of users apparently) by asking for ways of getting at their own stats. Pocket doesn't yet have a functionality for that internally, so I think there would be some hunger for a web app like this!

**Comment by nlbao** [comment]
Hey Jason, 

Thank you for the information and the photo.
I've just made the README more clear, hope it helps!

Wow, I didn't know there are many people interested in tracking their reading stats. Hope that I can have some time on this in the near future...
